name: SIT722 CI/CD – Backend + Frontend Deploy

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'k8s/**'
      - '.github/workflows/deploy.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}

      - name: Build & Push Backend
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/sit722-backend:${{ env.IMAGE_TAG }} backend
          docker push ${{ env.ACR_LOGIN_SERVER }}/sit722-backend:${{ env.IMAGE_TAG }}

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/sit722-frontend:${{ env.IMAGE_TAG }} frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/sit722-frontend:${{ env.IMAGE_TAG }}
